config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.delete
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :image_url, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h2>Add a new task</h2>

  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Edit flat", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats (<%= @flats.length %>)</h1>
  <ul class="list-unstyled">
    <% @flats.each do |flat| %>
      <li>
        <div id="cards-container" class="col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=flat.image_url%>);">
            <div class="card-category">Popular</div>
              <div class="card-description">
                <h2><%= flat.name %></h2>
                <p><%= flat.description %></p>
              </div>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
            <%= link_to 'More Infos', flat_path(flat), { :class=>"btn btn-primary card-btn" } %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/flats/new.html.erb
<div class="container">

  <h1>Flat#new</h1>
  <p>Find me in app/views/flats/new.html.erb</p>

  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :image_url %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "add a flat", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/flats/show.html.erb
<div id="photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @flat.image_url%>);"></div>

<div class="container">
  <div class="details-container">
      <div class="flat-infos">
        <div class="details-card">
          <h2> <%= @flat.name %> </h2>
          <p> <%= @flat.description %> </p>
          <p> <%= @flat.address %> </p>
        </div>
        <div class="details-card">
          <p> <%= @flat.price_per_night %> $</p>
          <p> <%= @flat.number_of_guests %> Guests</p>
        </div>
      </div>
      <div class="booking-form">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :number_of_guests %>
          <%= f.submit "book this flat", class: "btn btn-success" %>
        <% end %>
      </div>
  </div>
    <%= link_to 'Edit Flat Infos', edit_flat_path, :class => 'btn btn-primary' %>
    <%= link_to 'Delete Flat', flat_path(@flat), :class => 'btn btn-danger', method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
  </head>

  <body>

    <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= 'Simple Airbnb' %>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <!-- Links -->
        <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Add a flat", new_flat_path, { :class=>"btn btn-primary" } %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Some mobile link</a></li>
            <li><a href="#">Other one</a></li>
            <li><a href="#">Other one</a></li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>